# Generated by Django 3.1.2 on 2021-05-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cashdet',
        ),
        migrations.DeleteModel(
            name='Cashdet01',
        ),
        migrations.DeleteModel(
            name='Charge_sheet',
        ),
        migrations.DeleteModel(
            name='Comid',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Customer01',
        ),
        migrations.DeleteModel(
            name='Formnames',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.DeleteModel(
            name='Packages_S',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Trainee',
        ),
    ]
