# Generated by Django 3.1.2 on 2021-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_auto_20210531_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='pic',
            field=models.ImageField(blank=True, upload_to='traine'),
        ),
    ]
