# Generated by Django 3.1.2 on 2021-05-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_auto_20210531_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='contact',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
