# Generated by Django 3.1.2 on 2021-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_auto_20210531_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, default='trainee/defaultpic.png', null=True, upload_to='trainee/'),
        ),
    ]
