# Generated by Django 3.1.2 on 2021-05-31 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_auto_20210531_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='pic',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='member/defaultpic.png', null=True, upload_to='member/'),
        ),
        migrations.AddField(
            model_name='member',
            name='services',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.services'),
        ),
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='cnic',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='package',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='trainer',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
