# Generated by Django 3.1.2 on 2021-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0015_auto_20210601_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='services',
        ),
        migrations.AlterField(
            model_name='member',
            name='code',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(default='Surname', max_length=100),
        ),
    ]
