# Generated by Django 3.1.2 on 2021-06-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0019_auto_20210601_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='package',
            field=models.ForeignKey(default='---', null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.packages'),
        ),
    ]
