# Generated by Django 3.1.2 on 2021-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0021_auto_20210601_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='start',
            field=models.DateField(blank=True),
        ),
    ]
