# Generated by Django 3.1.2 on 2021-06-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0022_auto_20210601_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comid',
            old_name='comid',
            new_name='code',
        ),
    ]
