# Generated by Django 3.1.2 on 2021-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0023_auto_20210601_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comid',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='comid',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
