# Generated by Django 3.1.2 on 2021-06-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0024_auto_20210601_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge_sheet',
            name='code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
