# Generated by Django 3.1.2 on 2021-06-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0025_charge_sheet_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdet01',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.customer01'),
        ),
        migrations.AlterField(
            model_name='cashdet01',
            name='vouchtype',
            field=models.CharField(choices=[('BV', 'Bank Voucher'), ('CV', 'Cash Voucher'), ('JV', 'Journel Voucher')], default=0, max_length=30),
        ),
    ]
