# Generated by Django 3.1.2 on 2021-06-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0026_auto_20210608_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdet01',
            name='party',
        ),
    ]
