# Generated by Django 3.1.2 on 2021-06-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0027_remove_cashdet01_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdet01',
            name='party',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gymapp.customer01'),
            preserve_default=False,
        ),
    ]
