# Generated by Django 3.1.2 on 2021-06-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0032_auto_20210608_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdet01',
            name='date',
        ),
        migrations.AlterField(
            model_name='cashdet01',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gymapp.customer01'),
        ),
        migrations.AlterField(
            model_name='member',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.packages'),
        ),
    ]
