# Generated by Django 3.1.2 on 2021-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0033_auto_20210608_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdet01',
            name='partydescript',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='cashdet01',
            name='party',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
