# Generated by Django 3.1.2 on 2021-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0034_auto_20210608_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdet01',
            name='entrydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cashdet01',
            name='vouchtype',
            field=models.CharField(choices=[('BV', 'Bank Voucher'), ('CV', 'Cash Voucher'), ('JV', 'Journel Voucher')], max_length=30),
        ),
    ]
