# Generated by Django 3.1.2 on 2021-06-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0036_auto_20210609_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdet01',
            name='entrydate',
            field=models.DateTimeField(),
        ),
    ]
