# Generated by Django 3.1.2 on 2021-06-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0038_auto_20210609_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdet01',
            name='code',
            field=models.CharField(default=' ', max_length=100000),
            preserve_default=False,
        ),
    ]
