# Generated by Django 3.1.2 on 2021-06-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0039_cashdet01_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdet01',
            name='partydescript',
            field=models.CharField(max_length=30),
        ),
    ]
