# Generated by Django 3.1.2 on 2021-06-10 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0040_auto_20210609_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Admissionfee',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='lockerfee',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='lockerno',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='personaltrainerfee',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='trainerfee',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cashdet',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashdet',
            name='debit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashdet01',
            name='code',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='cashdet01',
            name='descript',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cashdet01',
            name='partydescript',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('due_amt', models.IntegerField(default=0)),
                ('due_date', models.DateField()),
                ('paid_amt', models.IntegerField()),
                ('paid_date', models.DateField()),
                ('balance', models.IntegerField()),
                ('vouchno', models.CharField(max_length=100)),
                ('member_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.member')),
            ],
        ),
    ]
