# Generated by Django 3.1.2 on 2021-06-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0041_auto_20210610_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(),
        ),
    ]
