# Generated by Django 3.1.2 on 2021-06-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0042_auto_20210610_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Totalfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='Admissionfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='lockerfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='personaltrainerfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='trainerfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='month',
            field=models.CharField(choices=[('01', 'Janurary'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022')], max_length=4),
        ),
    ]
