# Generated by Django 3.1.2 on 2021-06-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0043_auto_20210610_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Totalfee',
            new_name='totalfee',
        ),
    ]
