# Generated by Django 3.1.2 on 2021-06-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0044_auto_20210610_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='due_date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='member_code',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='gymapp.member'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='paid_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='paid_date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='vouchno',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
