# Generated by Django 3.1.2 on 2021-06-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0045_auto_20210610_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='paid_date',
            field=models.DateField(),
        ),
    ]
