# Generated by Django 3.1.2 on 2021-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0046_auto_20210610_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='Due', max_length=10),
            preserve_default=False,
        ),
    ]
