# Generated by Django 3.1.2 on 2021-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0047_transactions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='due_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='paid_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
