# Generated by Django 3.1.2 on 2021-06-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0049_auto_20210610_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('Due', 'Due'), ('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Due', max_length=10),
        ),
    ]
