# Generated by Django 3.1.2 on 2021-06-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0051_auto_20210610_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='start',
            field=models.DateField(),
        ),
    ]
