# Generated by Django 3.1.2 on 2021-06-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0052_auto_20210611_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='code',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='contact',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='followup_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='reference',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='remarks',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='service',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='surname',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.packages'),
        ),
    ]
