# Generated by Django 3.1.2 on 2021-06-29 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0054_auto_20210627_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdet01',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
